'use client'

import { useState, useEffect } from 'react'
import { Button } from '@/components/ui/button'
import ChatMessage from './chat-message'
import PersonaSwitcher from './persona-switcher'
import ConversationControls from './conversation-controls'
import GuestProfileCreator from './guest-profile-creator'
import { Send, RotateCcw, Share2 } from 'lucide-react'

const MOCK_CONVERSATION = [
  {
    id: 1,
    persona: 'host',
    name: 'ChatBotCast Host',
    message:
      "Welcome everyone! Today we're discussing the future of artificial intelligence. Let's dive into how AI will transform various industries.",
    timestamp: new Date(Date.now() - 5000),
  },
  {
    id: 2,
    persona: 'andrew-ng',
    name: 'Andrew Ng',
    message:
      'Thanks for having me. I believe the key transformation will come from practical applications. We need to focus on solving real problems rather than just chasing AGI.',
    timestamp: new Date(Date.now() - 4000),
  },
  {
    id: 3,
    persona: 'elon-musk',
    name: 'Elon Musk',
    message:
      'I think we should consider both timelines. Near-term applications are important, but we also need to think about long-term safety and alignment challenges.',
    timestamp: new Date(Date.now() - 3000),
  },
]

interface ChatConversationProps {
  data: any
  onPublish?: () => void
}

export default function ChatConversation({ data, onPublish }: ChatConversationProps) {
  const [messages, setMessages] = useState<any[]>(() => {
    console.log("[v0] ChatConversation received data:", data)
    if (data?.messages && Array.isArray(data.messages)) {
      return data.messages
    }
    return MOCK_CONVERSATION
  })

  const [nextSpeaker, setNextSpeaker] = useState<string | null>(null)
  const [isGenerating, setIsGenerating] = useState(false)
  const [turnMode] = useState(data?.turnMode || 'manual')
  const [numTurns] = useState(data?.numTurns || 3)
  const [currentCycleIndex, setCurrentCycleIndex] = useState(0)
  const [personas] = useState<string[]>(data?.personas || ['host', 'andrew-ng'])

  const persona_details: any = {
    'andrew-ng': { name: 'Andrew Ng', avatar: '🤖', color: 'from-blue-500 to-blue-600' },
    'elon-musk': { name: 'Elon Musk', avatar: '⚡', color: 'from-orange-500 to-red-600' },
    'sam-altman': { name: 'Sam Altman', avatar: '🧠', color: 'from-purple-500 to-pink-600' },
    'jane-goodall': { name: 'Jane Goodall', avatar: '🌍', color: 'from-green-500 to-emerald-600' },
    'bill-gates': { name: 'Bill Gates', avatar: '💡', color: 'from-cyan-500 to-blue-600' },
    'host': { name: 'ChatBotCast Host', avatar: '🎙️', color: 'from-slate-500 to-slate-600' },
    ...(data?.guestProfile && {
      [data.guestProfile.id]: {
        name: data.guestProfile.name,
        avatar: data.guestProfile.avatar,
        color: data.guestProfile.color,
        title: data.guestProfile.title,
      },
    }),
  }

  const handleEditMessage = (messageId: number, newText: string) => {
    setMessages(
      messages.map((msg) =>
        msg.id === messageId ? { ...msg, message: newText } : msg
      )
    )
  }

  const handleDeleteMessage = (messageId: number) => {
    setMessages(messages.filter((msg) => msg.id !== messageId))
  }

  const handleSelectSpeaker = (personaId: string) => {
    setNextSpeaker(personaId)
  }

  const handleGenerateResponse = async () => {
    const speakerToUse = nextSpeaker || personas[0]
    setIsGenerating(true)

    // Simulate API call
    await new Promise((resolve) => setTimeout(resolve, 1500))

    const personaDetail = persona_details[speakerToUse]
    const newMessage = {
      id: messages.length + 1,
      persona: speakerToUse,
      name: personaDetail.name,
      message: `This is a simulated response from ${personaDetail.name}. In a real implementation, this would be generated by calling your AI backend.`,
      timestamp: new Date(),
    }

    setMessages([...messages, newMessage])
    setIsGenerating(false)
    setNextSpeaker(null)

    // Auto-advance for certain modes
    if (turnMode === 'round-robin' || turnMode === 'alternating') {
      const nextIndex = (currentCycleIndex + 1) % personas.length
      setCurrentCycleIndex(nextIndex)
      setNextSpeaker(personas[nextIndex])
    }
  }

  const handleReset = () => {
    setMessages(MOCK_CONVERSATION)
    setNextSpeaker(null)
    setCurrentCycleIndex(0)
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Header with Publish Button */}
      <div className="space-y-2">
        <div className="flex items-start justify-between gap-4">
          <div className="flex-1">
            <h2 className="text-3xl md:text-4xl font-bold text-foreground">
              {data?.topic || 'New Conversation'}
            </h2>
            <p className="text-muted-foreground">
              {personas.length} personas • Mode: {turnMode}
            </p>
          </div>
          {onPublish && (
            <Button
              onClick={onPublish}
              className="bg-gradient-to-r from-accent to-orange-500 hover:opacity-90 whitespace-nowrap"
            >
              <Share2 className="h-4 w-4 mr-2" />
              Publish
            </Button>
          )}
        </div>
      </div>

      {/* Chat Area */}
      <div className="bg-white border border-border rounded-xl overflow-hidden flex flex-col h-96">
        {/* Messages */}
        <div className="flex-1 overflow-y-auto p-6 space-y-4">
          {messages.map((msg) => (
            <ChatMessage
              key={msg.id}
              message={msg}
              personaDetails={persona_details[msg.persona]}
              onEdit={handleEditMessage}
              onDelete={handleDeleteMessage}
            />
          ))}
          {isGenerating && (
            <div className="flex gap-3">
              <div className="h-8 w-8 rounded-full bg-muted flex items-center justify-center text-sm flex-shrink-0">
                ✨
              </div>
              <div className="flex items-center gap-2">
                <div className="h-2 w-2 bg-primary rounded-full animate-pulse"></div>
                <div className="h-2 w-2 bg-primary rounded-full animate-pulse" style={{ animationDelay: '0.2s' }}></div>
                <div className="h-2 w-2 bg-primary rounded-full animate-pulse" style={{ animationDelay: '0.4s' }}></div>
              </div>
            </div>
          )}
        </div>

        {/* Controls */}
        <div className="border-t border-border bg-background p-4 space-y-4">
          {turnMode === 'manual' && (
            <div className="space-y-2">
              <p className="text-xs font-semibold text-muted-foreground">Select who speaks next:</p>
              <PersonaSwitcher
                personas={personas}
                selected={nextSpeaker}
                onSelect={handleSelectSpeaker}
                personaDetails={persona_details}
              />
            </div>
          )}

          <Button
            onClick={handleGenerateResponse}
            disabled={isGenerating || (turnMode === 'manual' && !nextSpeaker)}
            className="w-full bg-gradient-to-r from-primary to-accent hover:opacity-90 disabled:opacity-50"
          >
            <Send className="h-4 w-4 mr-2" />
            {isGenerating ? 'Generating...' : 'Generate Response'}
          </Button>
        </div>
      </div>

      {/* Participants & Controls */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Participants */}
        <div className="lg:col-span-2 bg-white border border-border rounded-xl p-6">
          <h3 className="text-lg font-semibold text-foreground mb-4">Participants</h3>
          <div className="space-y-2">
            {personas.map((personaId: string) => {
              const detail = persona_details[personaId]
              return (
                <div
                  key={personaId}
                  className="flex items-center gap-3 p-3 bg-secondary rounded-lg border border-border/50"
                >
                  <div
                    className={`h-8 w-8 rounded-full bg-gradient-to-br ${detail.color} flex items-center justify-center text-sm flex-shrink-0`}
                  >
                    {detail.avatar}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="font-semibold text-sm text-foreground">{detail.name}</div>
                    {detail.title && <div className="text-sm text-muted-foreground">{detail.title}</div>}
                  </div>
                </div>
              )
            })}
            {data?.guestProfile && (
              <GuestProfileCreator
                guestProfile={data.guestProfile}
                personaDetails={persona_details}
              />
            )}
          </div>
        </div>

        {/* Conversation Info */}
        <div className="bg-white border border-border rounded-xl p-6">
          <h3 className="text-lg font-semibold text-foreground mb-4">Conversation</h3>
          <ConversationControls
            messageCount={messages.length}
            mode={turnMode}
            onReset={handleReset}
          />
        </div>
      </div>
    </div>
  )
}
